# Generated by Django 5.1.4 on 2025-01-12 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmallsShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('price', models.CharField(max_length=100)),
                ('products', models.JSONField()),
            ],
            options={
                'verbose_name': 'Emalls Shop',
                'verbose_name_plural': 'Emalls Shops',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('image_url', models.URLField()),
                ('store_count', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('product_id', models.CharField(max_length=100)),
                ('related_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dj_shops.emallsshop')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
