# Generated by Django 5.1.4 on 2025-01-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dj_shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_shop_token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emallsshop',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emallsshop',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emallsshop',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
