# Generated by Django 5.1.4 on 2025-01-12 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dj_shops', '0002_product_related_shop_token_alter_emallsshop_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='related_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dj_shops.emallsshop'),
        ),
    ]
